apiVersion: v2
name: actions-runner-controller
description: GitOps wrapper for GitHub Actions Runner Controller

type: application

version: 0.1.0

appVersion: "0.14.2"

dependencies:
  - name: gha-runner-scale-set-controller
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.14.2
