apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memos-minio-provisioning
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: memos-minio-provisioning
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.json: |
          {
            "version": "10",
            "aliases": {
              "homelab": {
                "url": "http://minio.minio.svc.cluster.local:9000",
                "accessKey": {{ `{{ .rootUser | toJson }}` }},
                "secretKey": {{ `{{ .rootPassword | toJson }}` }},
                "api": "S3v4",
                "path": "on"
              }
            }
          }
        user-credentials: |
          {{ .Values.memosStorage.user }}
          {{ `{{ .secretkey }}` }}
  data:
    - secretKey: rootUser
      remoteRef:
        key: secret/data/minio
        property: root-user
    - secretKey: rootPassword
      remoteRef:
        key: secret/data/minio
        property: root-password
    - secretKey: secretkey
      remoteRef:
        key: secret/data/memos/s3
        property: secretkey
