apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-root-credentials
  namespace: minio
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio-root-credentials
    creationPolicy: Owner
  data:
  - secretKey: root-user
    remoteRef:
      key: secret/data/minio
      property: root-user
  - secretKey: root-password
    remoteRef:
      key: secret/data/minio
      property: root-password
