apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
secrets:
  - name: homepage
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    kubernetes.io/service-account.name: homepage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: false
      hideVisitURL: true
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - k8s Repo:
            - abbr: GH
              icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/github-light.png
              href: https://github.com/shivppatel/k8s
        - k8s PRs:
            - abbr: GH
              icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/github-light.png
              href: https://github.com/Shivppatel/k8s/pulls
        - k8s GHA:
            - abbr: GH
              icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/github-light.png
              href: https://github.com/Shivppatel/k8s/actions
  services.yaml: |
    - Observability:
        - Alloy:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/alloy.png
            href: https://alloy.shivpatel.xyz
            description: Collectors and stuff
        - Datadog:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/datadog.png
            href: https://app.datadoghq.com/dashboard/lists?p=1
            description: Dashbaords and stuff
        - Grafana:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/grafana.png
            href: https://grafana.shivpatel.xyz
            description: Dashbaords and stuff
        - Kibana:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/kibana.png
            href: https://kibana.shivpatel.xyz
            description: ES dashboards and stuff
        - Policy Reporter:
            icon: https://kyverno.github.io/policy-reporter-docs/logo.png
            href: https://policy-reporter.shivpatel.xyz
            description: Policies and stuff
        - Prometheus:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/prometheus.png
            href: https://prometheus.shivpatel.xyz
            description: Metrics and stuff
        - Uptime Kuma:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/uptime-kuma.png
            href: https://uptime.shivpatel.xyz/dashboard
            description: Uptime and stuff

    - Admin:
        - Argocd:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/argo-cd.png
            href: https://argocd.shivpatel.xyz
            description: ArgoCD and stuff
        - Gitea:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/gitea.png
            href: https://gitea.shivpatel.xyz
            description: Source control and stuff
        - Harbor:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/harbor.png
            href: https://harbor.shivpatel.xyz
            description: Registries and stuff
        - Headlamp:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/headlamp.png
            href: https://headlamp.shivpatel.xyz
            description: Clusters and stuff
        - Keycloak:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/keycloak.png
            href: https://keycloak.shivpatel.xyz
            description: Access management and stuff
        - Longhorn:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/longhorn.png
            href: https://longhorn.shivpatel.xyz
            description: Storage and stuff
        - Portainer:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/portainer-dark.png
            href: https://portainer.shivpatel.xyz
            description: Containers and stuff
        - Traefik:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/traefik-proxy.png
            href: https://traefik.shivpatel.xyz/dashboard/#/
            description: Ingress and stuff

    - Apps:
        - MiniO:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/minio.png
            href: https://minio.shivpatel.xyz/
            description: Objects and stuff
        - n8n:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/n8n.png
            href: https://n8n.shivpatel.xyz
            description: Automations and stuff
        - Open WebUI:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/open-webui.png
            href: https://chat.shivpatel.xyz
            description: Local AI models and stuff
        - OpenCost:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/opencost.png
            href: https://opencost.shivpatel.xyz/
            description: Costs and stuff
        - pgAdmin:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/pgadmin.png
            href: https://pgadmin.shivpatel.xyz/
            description: DBs and stuff
        - RabbitMQ:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/rabbitmq.png
            href: https://rabbitmq.shivpatel.xyz/
            description: Messages and stuff
        - Teslamate:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/teslamate-light.png
            href: https://tesla.shivpatel.xyz/
            description: Data and stuff
        - Vault:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/hashicorp-vault.png
            href: https://vault.shivpatel.xyz
            description: Secrets and stuff

    - Home:
        - Pi-hole:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/pi-hole-unbound.png
            href: https://pihole.shivpatel.xyz/
            description: Holes and stuff
        - Nextcloud:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/nextcloud.png
            href: https://nextcloud.shivpatel.xyz
            description: Personal cloud and stuff
        - Home Assistant:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/home-assistant.png
            href: https://home.shivpatel.xyz
            description: IoT and stuff
        - Immich:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/immich.png
            href: https://immich.shivpatel.xyz
            description: Photos and stuff
        - It-Tools:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/it-tools-light.png
            href: https://tools.shivpatel.xyz
            description: Tools and stuff
        - Jellyfin:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/jellyfin.png
            href: https://jelly.shivpatel.xyz
            description: Linux ISOs and stuff
        - Unifi:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/unifi.png
            href: https://unifi.ui.com
            description: Networking and stuff

  widgets.yaml: |
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: google
        showSearchSuggestions: true
        target: _blank
    - datetime:
        text_size: 2xl
        format:
          timeStyle: short
          hour12: true
  docker.yaml: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
  - apiGroups:
      - traefik.io
    resources:
      - ingressroutes
    verbs:
      - get
      - list
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - httproutes
      - gateways
    verbs:
      - get
      - list
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: homepage
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: homepage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: homepage
          image: "ghcr.io/gethomepage/homepage:latest"
          imagePullPolicy: Always
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: shivpatel.xyz,homepage.shivpatel.xyz # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/config/custom.js
              name: homepage-config
              subPath: custom.js
            - mountPath: /app/config/custom.css
              name: homepage-config
              subPath: custom.css
            - mountPath: /app/config/bookmarks.yaml
              name: homepage-config
              subPath: bookmarks.yaml
            - mountPath: /app/config/docker.yaml
              name: homepage-config
              subPath: docker.yaml
            - mountPath: /app/config/kubernetes.yaml
              name: homepage-config
              subPath: kubernetes.yaml
            - mountPath: /app/config/services.yaml
              name: homepage-config
              subPath: services.yaml
            - mountPath: /app/config/settings.yaml
              name: homepage-config
              subPath: settings.yaml
            - mountPath: /app/config/widgets.yaml
              name: homepage-config
              subPath: widgets.yaml
            - mountPath: /app/config/logs
              name: logs
      volumes:
        - name: homepage-config
          configMap:
            name: homepage
        - name: logs
          emptyDir: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage-ingress
  namespace: homepage
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`homepage.shivpatel.xyz`)
    kind: Rule
    services:
    - name: homepage
      port: 3000
  tls: {}