apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
secrets:
  - name: homepage
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    kubernetes.io/service-account.name: homepage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    providers:
      longhorn:
        url: https://longhorn.shivpatel.xyz
    background: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: false
      hideVisitURL: true
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - k8s Repo:
            - abbr: GH
              icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/github-light.png
              href: https://github.com/shivppatel/k8s
        - k8s PRs:
            - abbr: GH
              icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/github-light.png
              href: https://github.com/Shivppatel/k8s/pulls
        - k8s GHA:
            - abbr: GH
              icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/github-light.png
              href: https://github.com/Shivppatel/k8s/actions
  services.yaml: |
    - Observability:
        - Datadog:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/datadog.png
            href: https://app.datadoghq.com/dashboard/lists?p=1
            description: Dashbaords and stuff
        - Grafana:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/grafana.png
            href: https://grafana.shivpatel.xyz
            description: Dashbaords and stuff
        - Prometheus:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/prometheus.png
            href: https://prometheus.shivpatel.xyz
            description: Metrics and stuff
        - Alloy:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/alloy.png
            href: https://alloy.shivpatel.xyz
            description: Collectors and stuff

    - Admin:
        - Argocd:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/argo-cd.png
            href: https://argocd.shivpatel.xyz
            description: ArgoCD and stuff
            ping: https://argocd.shivpatel.xyz
        - Traefik:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/traefik-proxy.png
            href: https://traefik.shivpatel.xyz/dashboard/#/
            description: Ingress and stuff
        - Longhorn:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/longhorn.png
            href: https://longhorn.shivpatel.xyz
            description: Storage and stuff

    - Apps:
        - Pi-hole:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/pi-hole-unbound.png
            href: https://pihole.shivpatel.xyz/admin
            description: Holes and stuff
        - Vault:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/vault-light.png
            href: https://vault.shivpatel.xyz
            description: Secrets and stuff
        - Homepage:
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/homepage.png
            href: https://homepage.shivpatel.xyz
            description: Homepage and stuff

  widgets.yaml: |
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: google
        showSearchSuggestions: true
        target: _blank
    - datetime:
        text_size: 2xl
        format:
          timeStyle: short
          hour12: true
  docker.yaml: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
  - apiGroups:
      - traefik.io
    resources:
      - ingressroutes
    verbs:
      - get
      - list
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - httproutes
      - gateways
    verbs:
      - get
      - list
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: homepage
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: homepage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: homepage
          image: "ghcr.io/gethomepage/homepage:latest"
          imagePullPolicy: Always
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: homepage.shivpatel.xyz # required, may need port. See gethomepage.dev/installation/#homepage_allowed_hosts
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /app/config/custom.js
              name: homepage-config
              subPath: custom.js
            - mountPath: /app/config/custom.css
              name: homepage-config
              subPath: custom.css
            - mountPath: /app/config/bookmarks.yaml
              name: homepage-config
              subPath: bookmarks.yaml
            - mountPath: /app/config/docker.yaml
              name: homepage-config
              subPath: docker.yaml
            - mountPath: /app/config/kubernetes.yaml
              name: homepage-config
              subPath: kubernetes.yaml
            - mountPath: /app/config/services.yaml
              name: homepage-config
              subPath: services.yaml
            - mountPath: /app/config/settings.yaml
              name: homepage-config
              subPath: settings.yaml
            - mountPath: /app/config/widgets.yaml
              name: homepage-config
              subPath: widgets.yaml
            - mountPath: /app/config/logs
              name: logs
      volumes:
        - name: homepage-config
          configMap:
            name: homepage
        - name: logs
          emptyDir: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage-ingress
  namespace: homepage
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`homepage.shivpatel.xyz`)
    kind: Rule
    services:
    - name: homepage
      port: 3000