image:
  repository: ghcr.io/gethomepage/homepage
  tag: "latest@sha256:da9dca9ec258c628146bed1445da0853f2b88f0b10bafd97c091de807c363d60"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  host: homepage.shivpatel.xyz

allowedHosts: "shivpatel.xyz,homepage.shivpatel.xyz"

externalSecret:
  enabled: true
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  vaultPath: secret/data/homepage
