apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: elasticsearch-master-credentials
  namespace: logging
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: elasticsearch-master-credentials
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: secret/data/elasticsearch/credentials
      property: password
  - secretKey: username
    remoteRef:
      key: secret/data/elasticsearch/credentials
      property: username
