apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-password-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: redis-password-secret
    creationPolicy: Owner
  data:
    - secretKey: redis-password
      remoteRef:
        key: secret/data/redis
        property: redis-password
