apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-db-secret
  namespace: n8n
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: n8n-db-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_POSTGRESDB_USER
      remoteRef:
        key: secret/data/postgresql/n8n
        property: username
    - secretKey: DB_POSTGRESDB_PASSWORD
      remoteRef:
        key: secret/data/postgresql/n8n
        property: password
