{{- range $name, $share := .Values.nfsShares }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-nfs-{{ $name }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: {{ $share.capacity | default "1Ti" }}
  volumeName: jellyfin-nfs-{{ $name }}
{{- end }}
