{{- range $name, $share := .Values.nfsShares }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-nfs-{{ $name }}
spec:
  capacity:
    storage: {{ $share.capacity | default "1Ti" }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=3
    - rsize=131072
    - wsize=131072
    - nconnect=8
    - noatime
    - nodiratime
  nfs:
    path: {{ $share.path }}
    server: {{ $share.server }}
{{- end }}
