apiVersion: v2
name: loki
description: A Helm chart for Loki

type: application

version: 0.1.0

appVersion: "3.6.2"

dependencies:
  - name: loki
    repository: https://grafana.github.io/helm-charts
    version: 6.48.0
