apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: elasticsearch-master-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: elasticsearch-master-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secret/data/elasticsearch
        property: username
    - secretKey: password
      remoteRef:
        key: secret/data/elasticsearch
        property: password
