cert-manager:
  replicaCount: 3
  podAnnotations:
    ad.datadoghq.com/cert-manager-controller.logs: |
      [
        {
          "source": "cert_manager",
          "service": "cert-manager-controller"
        }
      ]
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  prometheus:
    servicemonitor:
      enabled: true
  webhook:
    podAnnotations:
      ad.datadoghq.com/cert-manager-webhook.logs: |
        [
          {
            "source": "cert_manager",
            "service": "cert-manager-webhook"
          }
        ]
  cainjector:
    podAnnotations:
      ad.datadoghq.com/cert-manager-cainjector.logs: |
        [
          {
            "source": "cert_manager",
            "service": "cert-manager-cainjector"
          }
        ]
  crds:
    enabled: true
