apiVersion: v1
kind: Service
metadata:
  name: actions-runner-controller-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: actions-runner-controller
    app.kubernetes.io/name: gha-rs-controller
spec:
  selector:
    app.kubernetes.io/instance: actions-runner-controller
    app.kubernetes.io/name: gha-rs-controller
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
