apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: actions-runner-controller
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: actions-runner-controller
      app.kubernetes.io/name: gha-rs-controller
