apiVersion: v2
name: datadog-operator
description: A Helm chart for Datadog Operator

type: application

version: 0.1.0

appVersion: "1.24.0-rc.2"

dependencies:
  - name: datadog-operator
    repository: https://helm.datadoghq.com
    version: 2.19.0-dev.7
