FROM gcr.io/datadoghq/agent:7.74.0-jmx@sha256:94d356fe1ea92cd64b64de2f6c368e97e988130f033ce83aa500e2933fbabbf9

LABEL org.opencontainers.image.source="https://github.com/Shivppatel/k8s"
LABEL org.opencontainers.image.description="Datadog Agent with EMQX, Grafana, and Nextcloud community integrations"

RUN agent integration install -r -t datadog-emqx==1.1.0
RUN agent integration install -r -t datadog-grafana==1.0.0
RUN agent integration install -r -t datadog-nextcloud==2.0.0
