apiVersion: v2
name: datadog-operator
description: A Helm chart for Datadog Operator

type: application

version: 0.1.0

appVersion: "1.19.1"

dependencies:
  - name: datadog-operator
    repository: https://helm.datadoghq.com
    version: 2.14.3
