replicaCount: 1

image:
  repository: neosmemo/memos
  tag: "0.31.0"
  digest: sha256:24c2707ddd8fbd2ceaa7a61ecab86a53cdcde640b24ce572b73da14b00b5785f
  pullPolicy: IfNotPresent

minioClient:
  image: docker.io/bitnamilegacy/minio-client:2025.7.21-debian-12-r2

service:
  port: 5230

ingress:
  host: memos.shivpatel.xyz

storage:
  id: minio-attachments
  bucket: memos-attachments
  endpoint: http://minio.minio.svc.cluster.local:9000
  region: us-east-1
  uploadSizeLimitMb: 30

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "1"
    memory: "512Mi"
