apiVersion: v2
name: github-actions-runners
description: Autoscaled, ephemeral GitHub Actions runners for private GitOps workflows

type: application

version: 0.1.0

appVersion: "0.14.2"

dependencies:
  - name: gha-runner-scale-set
    repository: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.14.2
