apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-db-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: immich-db-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: secret/data/postgresql/immich
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/data/postgresql/immich
        property: password
