apiVersion: v1
kind: Secret
metadata:
  name: immich-postgres-app
  namespace: immich
type: Opaque
stringData:
  username: immich
  password: changeme-immich-password
  database: immich
  host: immich-postgres-rw
  port: "5432"
