apiVersion: v2
name: openspeedtest
description: A Helm chart for OpenSpeedTest

type: application

version: 0.1.0

appVersion: "v2.0.0"

dependencies:
  - name: openspeedtest
    repository: https://openspeedtest.github.io/Helm-chart/
    version: 0.1.2
