apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: caretta
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: caretta
      app.kubernetes.io/instance: {{ .Release.Name }}
  podMetricsEndpoints:
    - port: prom-metrics
      path: /metrics
      interval: 15s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: caretta_node
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: caretta_pod
