apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-cloudflare-secret
  namespace: external-dns
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: external-cloudflare-secret
    creationPolicy: Owner
  data:
    - secretKey: apiKey
      remoteRef:
        key: secret/data/cloudflare/external-dns
        property: apiKey
