nextcloud:
  nextcloud:
    host: nextcloud.shivpatel.xyz
    existingSecret:
      enabled: true
      secretName: nextcloud-secret
      usernameKey: nextcloud-username
      passwordKey: nextcloud-password
    extraVolumes:
      - name: apache-status
        configMap:
          name: nextcloud-apache-status
    extraVolumeMounts:
      - name: apache-status
        mountPath: /etc/apache2/conf-enabled/datadog-status.conf
        subPath: datadog-status.conf
        readOnly: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  podAnnotations:
    ad.datadoghq.com/nextcloud.checks: |
      {
        "apache": {
          "init_config": {},
          "instances": [
            {
              "apache_status_url": "http://%%host%%:8081/server-status?auto",
              "service": "nextcloud-apache"
            }
          ]
        }
      }
    ad.datadoghq.com/nextcloud.logs: |
      [
        {
          "source": "apache",
          "service": "nextcloud-apache"
        }
      ]
  persistence:
    enabled: true
    # using default storageclass (longhorn) for core files
  nextcloudData:
    enabled: true
    existingClaim: nextcloud-nfs
