nextcloud:
  nextcloud:
    host: nextcloud.shivpatel.xyz
    existingSecret:
      enabled: true
      secretName: nextcloud-secret
      usernameKey: nextcloud-username
      passwordKey: nextcloud-password
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    extraVolumes:
      - name: rsync-wrapper
        configMap:
          name: nextcloud-rsync-wrapper
          defaultMode: 0755
    extraVolumeMounts:
      - name: rsync-wrapper
        mountPath: /usr/local/bin/rsync
        subPath: rsync
  persistence:
    enabled: true
    existingClaim: nextcloud-nfs
