rabbitmq:
  global:
    security:
      allowInsecureImages: true
  image:
    registry: docker.io
    repository: bitnamilegacy/rabbitmq
  updateStrategy:
    type: OnDelete
  auth:
    # Use existing secret from Vault via ExternalSecret
    existingPasswordSecret: rabbitmq
    existingErlangSecret: rabbitmq
    # Force password update even with existing persisted data
    forcePassword: true
  podAnnotations:
    ad.datadoghq.com/rabbitmq.checks: |
      {
        "rabbitmq": {
          "init_config": {},
          "instances": [
            {
              "prometheus_plugin": {
                "url": "http://%%host%%:9419"
              }
            }
          ]
        }
      }
    ad.datadoghq.com/rabbitmq.logs: |
      [
        {
          "source": "rabbitmq",
          "service": "rabbitmq",
          "log_processing_rules": [
            {
              "type": "multi_line",
              "name": "logs_starts_with_equal_sign",
              "pattern": "="
            }
          ]
        }
      ]
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
