apiVersion: v2
name: policy-reporter
description: A Helm chart for Kyverno Policy Reporter

type: application

version: 0.1.0

appVersion: "3.5.0"

dependencies:
  - name: policy-reporter
    repository: https://kyverno.github.io/policy-reporter
    version: 3.7.2
