traefik:
  ingressRoute:
    dashboard:
      enabled: true

  logs:
    general:
      level: "INFO" # DEBUG if needed
      format: json
    access:
      enabled: true
      format: json
      addInternals: false
      fields:
        headers:
          defaultmode: drop

  service:
    type: LoadBalancer
    loadBalancerIP: "192.168.20.20" # Choose an available IP from your MetalLB range

  additionalArguments:
    - --entryPoints.web.http.redirections.entryPoint.to=websecure
    - --entryPoints.web.http.redirections.entryPoint.scheme=https
    - --entryPoints.web.http.redirections.entryPoint.permanent=true
    - --entryPoints.websecure.http.middlewares=traefik-security-headers@kubernetescrd
    - --tracing.addinternals=true
    - --tracing.otlp=true
    - --tracing.otlp.grpc=true
    - --tracing.otlp.grpc.endpoint=alloy.observability.svc.cluster.local:4317
    - --tracing.otlp.grpc.insecure=true
    - --api.debug=true
    - --api.insecure=true

  tlsStore:
    default:
      defaultCertificate:
        secretName: wildcard-cert-new

  persistence:
    enabled: false

  deployment:
    replicas: 3
    podAnnotations:
      profiles.grafana.com/cpu.scrape: "true"
      profiles.grafana.com/cpu.port_name: "traefik"
      profiles.grafana.com/memory.scrape: "true"
      profiles.grafana.com/memory.port_name: "traefik"
      profiles.grafana.com/goroutine.scrape: "true"
      profiles.grafana.com/goroutine.port_name: "traefik"

  metrics:
    addInternals: true
    prometheus:
      addRoutersLabels: true
      addServicesLabels: true
      serviceMonitor:
        enabled: true
        honorLabels: true
