apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coder-db-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: coder-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        url: 'postgresql://{{ `{{ .username | urlquery }}` }}:{{ `{{ .password | urlquery }}` }}@postgresql-rw.postgresql.svc.cluster.local:5432/coder?sslmode=require'
  data:
    - secretKey: username
      remoteRef:
        key: secret/data/postgresql/coder
        property: username
    - secretKey: password
      remoteRef:
        key: secret/data/postgresql/coder
        property: password
