apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: coder
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: coder
      app.kubernetes.io/instance: {{ .Release.Name }}
  podMetricsEndpoints:
    - port: prometheus-http
      interval: 30s
