apiVersion: v1
kind: ServiceAccount
metadata:
  name: coder-workspace
  namespace: coder-workspaces
  labels:
    app.kubernetes.io/name: coder-workspace
    app.kubernetes.io/part-of: coder-workspaces
automountServiceAccountToken: false
