apiVersion: v2
name: outline
description: A Helm chart for Outline

type: application

version: 0.1.0

appVersion: "1.1.0"

dependencies:
  - name: outline
    repository: https://community-charts.github.io/helm-charts
    version: 0.7.3
