{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-widget-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Release.Name }}-widget-credentials
    creationPolicy: Owner
  data:
    - secretKey: HOMEPAGE_VAR_ARGOCD_KEY
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: argocd-key
    - secretKey: HOMEPAGE_VAR_CLOUDFLARE_KEY
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: cloudflare-key
    - secretKey: HOMEPAGE_VAR_GRAFANA_USERNAME
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: grafana-username
    - secretKey: HOMEPAGE_VAR_GRAFANA_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: grafana-password
    - secretKey: HOMEPAGE_VAR_GITEA_KEY
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: gitea-key
    - secretKey: HOMEPAGE_VAR_HOMEASSISTANT_KEY
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: homeassistant-key
    - secretKey: HOMEPAGE_VAR_IMMICH_KEY
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: immich-key
    - secretKey: HOMEPAGE_VAR_JELLYFIN_KEY
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: jellyfin-key
    - secretKey: HOMEPAGE_VAR_NEXTCLOUD_USERNAME
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: nextcloud-username
    - secretKey: HOMEPAGE_VAR_NEXTCLOUD_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: nextcloud-password
    - secretKey: HOMEPAGE_VAR_PIHOLE_KEY
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: pihole-key
    - secretKey: HOMEPAGE_VAR_GOOGLE_ICAL
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: google-ical
    - secretKey: HOMEPAGE_VAR_WORK_ICAL
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: work-ical
{{- end }}
