apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-nfs
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi
  volumeName: nextcloud-nfs
