apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: nextcloud-secret
    creationPolicy: Owner
  data:
    - secretKey: nextcloud-username
      remoteRef:
        key: secret/data/nextcloud/
        property: username
    - secretKey: nextcloud-password
      remoteRef:
        key: secret/data/nextclouad
        property: password
