apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memos-storage-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: memos-storage-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        memos-instance-setting-storage.json: |
          {
            "key": "STORAGE",
            "storageSetting": {
              "filepathTemplate": "assets/{timestamp}_{uuid}_{filename}",
              "uploadSizeLimitMb": {{ .Values.storage.uploadSizeLimitMb | toString | quote }},
              "defaultStorageId": {{ .Values.storage.id | quote }},
              "storages": [{
                "id": {{ .Values.storage.id | quote }},
                "name": "MinIO attachments",
                "type": "STORAGE_TYPE_S3",
                "s3Config": {
                  "accessKeyId": {{ `{{ .accesskey | toJson }}` }},
                  "accessKeySecret": {{ `{{ .secretkey | toJson }}` }},
                  "endpoint": {{ .Values.storage.endpoint | quote }},
                  "region": {{ .Values.storage.region | quote }},
                  "bucket": {{ .Values.storage.bucket | quote }},
                  "usePathStyle": true,
                  "insecureSkipTlsVerify": false
                }
              }]
            }
          }
        config.json: |
          {
            "version": "10",
            "aliases": {
              "memos": {
                "url": {{ .Values.storage.endpoint | quote }},
                "accessKey": {{ `{{ .accesskey | toJson }}` }},
                "secretKey": {{ `{{ .secretkey | toJson }}` }},
                "api": "S3v4",
                "path": "on"
              }
            }
          }
  data:
    - secretKey: accesskey
      remoteRef:
        key: secret/data/memos/s3
        property: accesskey
    - secretKey: secretkey
      remoteRef:
        key: secret/data/memos/s3
        property: secretkey
