apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: memos-ingress
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: memos
          port: {{ .Values.service.port }}
  tls: {}
