apiVersion: v1
kind: Service
metadata:
  name: memos
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: memos
