apiVersion: v2
name: metrics-server
description: A Helm chart for metrics-server

type: application

version: 0.1.0

appVersion: "0.8.0"

dependencies:
  - name: metrics-server
    repository: https://kubernetes-sigs.github.io/metrics-server/
    version: 3.13.0
