apiVersion: v2
name: uptime-kuma
description: A Helm chart for Uptime Kuma

type: application

version: 0.1.0

appVersion: "2.0.2"

dependencies:
  - name: uptime-kuma
    repository: https://dirsigler.github.io/uptime-kuma-helm
    version: 2.24.0
