apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-superuser
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgresql-superuser
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secret/data/postgresql/admin
        property: username
    - secretKey: password
      remoteRef:
        key: secret/data/postgresql/admin
        property: password
---
# Secret for CNPG managed role - immich
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-db-secret
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: immich-db-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secret/data/postgresql/immich
        property: username
    - secretKey: password
      remoteRef:
        key: secret/data/postgresql/immich
        property: password
---
# Secret for CNPG managed role - keycloak
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-secret
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-db-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secret/data/postgresql/keycloak
        property: username
    - secretKey: password
      remoteRef:
        key: secret/data/postgresql/keycloak
        property: password
