apiVersion: batch/v1
kind: Job
metadata:
  name: postgresql-setup
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: immich-db-secret
          secret:
            secretName: immich-db-secret
        - name: keycloak-db-secret
          secret:
            secretName: keycloak-db-secret
        - name: n8n-db-secret
          secret:
            secretName: n8n-db-secret
        - name: teslamate-db-secret
          secret:
            secretName: teslamate-db-secret
      containers:
        - name: setup
          image: ghcr.io/cloudnative-pg/postgresql:17
          env:
            - name: PGHOST
              value: postgresql-rw.postgresql.svc.cluster.local
            # CNPG auto-generates this secret: <cluster-name>-superuser
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgresql-superuser
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-superuser
                  key: password
          volumeMounts:
            - name: immich-db-secret
              mountPath: /run/secrets/immich-db-secret
            - name: keycloak-db-secret
              mountPath: /run/secrets/keycloak-db-secret
            - name: n8n-db-secret
              mountPath: /run/secrets/n8n-db-secret
            - name: teslamate-db-secret
              mountPath: /run/secrets/teslamate-db-secret
          command:
            - /bin/bash
            - -c
            - |
              set -e
              
              # Wait for PostgreSQL to be ready
              until pg_isready -h $PGHOST -p 5432 -U $PGUSER; do
                echo "Waiting for PostgreSQL..."
                sleep 2
              done
              
              # Ensure all users and databases exist (idempotent)
              for app in immich keycloak n8n teslamate; do
                echo "Ensuring $app user and database exist..."
                psql -c "DO \$\$ BEGIN CREATE USER $app WITH PASSWORD 'temp'; EXCEPTION WHEN duplicate_object THEN NULL; END \$\$;"
                psql -c "SELECT 1 FROM pg_database WHERE datname='$app'" | grep -q 1 || psql -c "CREATE DATABASE $app OWNER $app;"
              done
              
              echo "Setting up immich database..."
              psql -d immich -c "CREATE EXTENSION IF NOT EXISTS cube;"
              psql -d immich -c "CREATE EXTENSION IF NOT EXISTS earthdistance;"
              psql -d immich -c "CREATE EXTENSION IF NOT EXISTS vector;"
              psql -d immich -c "ALTER SCHEMA public OWNER TO immich;"
              psql -d immich -c "GRANT ALL ON SCHEMA public TO immich;"
              
              echo "Setting up keycloak database..."
              psql -d keycloak -c "ALTER SCHEMA public OWNER TO keycloak;"
              psql -d keycloak -c "GRANT ALL ON SCHEMA public TO keycloak;"
              
              echo "Setting up n8n database..."
              psql -d n8n -c "ALTER SCHEMA public OWNER TO n8n;"
              psql -d n8n -c "GRANT ALL ON SCHEMA public TO n8n;"
              
              echo "Setting up teslamate database..."
              psql -d teslamate -c "ALTER SCHEMA public OWNER TO teslamate;"
              psql -d teslamate -c "GRANT ALL ON SCHEMA public TO teslamate;"
              
              # Sync passwords from ExternalSecrets to database users
              echo "Syncing passwords from ExternalSecrets..."
              # Read secrets directly from mounted files or environment variables
              for app in immich keycloak n8n teslamate; do
                echo "Syncing password for $app..."
                # Use environment variables or mount secrets as files
                PASSWORD=$(cat /run/secrets/${app}-db-secret/password 2>/dev/null || echo "")
                if [ -z "$PASSWORD" ]; then
                  echo "Warning: Could not read password for $app, keeping existing password"
                else
                  psql -c "ALTER USER $app WITH PASSWORD '$PASSWORD';"
                fi
              done

              echo "Setup complete!"
