apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atlantis-tf-secrets
  namespace: atlantis
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: atlantis-tf-secrets
    creationPolicy: Owner
  data:
    # Cloudflare
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: secret/data/terraform/cloudflare
        property: api_token
    - secretKey: TF_VAR_zone_id
      remoteRef:
        key: secret/data/terraform/cloudflare
        property: zone_id
    - secretKey: TF_VAR_account_id
      remoteRef:
        key: secret/data/terraform/cloudflare
        property: account_id
    - secretKey: TF_VAR_tunnel_id
      remoteRef:
        key: secret/data/terraform/cloudflare
        property: tunnel_id

    # Datadog
    - secretKey: DD_API_KEY
      remoteRef:
        key: secret/data/terraform/datadog
        property: api_key
    - secretKey: DD_APP_KEY
      remoteRef:
        key: secret/data/terraform/datadog
        property: app_key

    # Authentik
    - secretKey: AUTHENTIK_URL
      remoteRef:
        key: secret/data/terraform/authentik
        property: url
    - secretKey: AUTHENTIK_TOKEN
      remoteRef:
        key: secret/data/terraform/authentik
        property: token

    # Gitea
    - secretKey: GITEA_BASE_URL
      remoteRef:
        key: secret/data/terraform/gitea
        property: base_url
    - secretKey: GITEA_TOKEN
      remoteRef:
        key: secret/data/terraform/gitea
        property: token

    # Grafana
    - secretKey: GRAFANA_URL
      remoteRef:
        key: secret/data/terraform/grafana
        property: url
    - secretKey: GRAFANA_AUTH
      remoteRef:
        key: secret/data/terraform/grafana
        property: auth

    # MinIO
    - secretKey: MINIO_ENDPOINT
      remoteRef:
        key: secret/data/terraform/minio
        property: endpoint
    - secretKey: MINIO_USER
      remoteRef:
        key: secret/data/terraform/minio
        property: user
    - secretKey: MINIO_PASSWORD
      remoteRef:
        key: secret/data/terraform/minio
        property: password

    # PostgreSQL
    - secretKey: PGHOST
      remoteRef:
        key: secret/data/terraform/postgresql
        property: host
    - secretKey: PGUSER
      remoteRef:
        key: secret/data/terraform/postgresql
        property: user
    - secretKey: PGPASSWORD
      remoteRef:
        key: secret/data/terraform/postgresql
        property: password

    # RabbitMQ
    - secretKey: RABBITMQ_ENDPOINT
      remoteRef:
        key: secret/data/terraform/rabbitmq
        property: endpoint
    - secretKey: RABBITMQ_USERNAME
      remoteRef:
        key: secret/data/terraform/rabbitmq
        property: username
    - secretKey: RABBITMQ_PASSWORD
      remoteRef:
        key: secret/data/terraform/rabbitmq
        property: password

    # Kafka
    - secretKey: KAFKA_BOOTSTRAP_SERVERS
      remoteRef:
        key: secret/data/terraform/kafka
        property: bootstrap_servers

    # Vault (for tf/vault/ module)
    - secretKey: VAULT_ADDR
      remoteRef:
        key: secret/data/terraform/vault
        property: addr
    - secretKey: VAULT_TOKEN
      remoteRef:
        key: secret/data/terraform/vault
        property: token

    # PG Backend (Terraform state connection string)
    - secretKey: PG_CONN_STR
      remoteRef:
        key: secret/data/terraform/pg-backend
        property: conn_str
