apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-secret
  namespace: atlantis
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: github-secret
    creationPolicy: Owner
  data:
    # GitHub App creds for Atlantis
    - secretKey: ATLANTIS_GH_APP_ID
      remoteRef:
        key: secret/data/github/atlantis
        property: app_id
    - secretKey: ATLANTIS_GH_APP_CLIENT_ID
      remoteRef:
        key: secret/data/github/atlantis
        property: client_id
    - secretKey: ATLANTIS_GH_APP_CLIENT_SECRET
      remoteRef:
        key: secret/data/github/atlantis
        property: client_secret
    - secretKey: ATLANTIS_GH_APP_KEY
      remoteRef:
        key: secret/data/github/atlantis
        property: key
    - secretKey: ATLANTIS_GH_APP_SLUG
      remoteRef:
        key: secret/data/github/atlantis
        property: slug
    - secretKey: ATLANTIS_GH_WEBHOOK_SECRET
      remoteRef:
        key: secret/data/github/atlantis
        property: webhook_secret
    - secretKey: ATLANTIS_GH_APP_INSTALLATION_ID
      remoteRef:
        key: secret/data/github/atlantis
        property: installation_id
