apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-nfs
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 500Gi
  volumeName: immich-nfs
