apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-v2
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
