apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin-credentials
  namespace: keycloak
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-admin-credentials
    creationPolicy: Owner
  data:
  - secretKey: admin-password
    remoteRef:
      key: secret/data/keycloak/admin
      property: password
