apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
  labels:
    app.kubernetes.io/name: uptime-kuma
    app.kubernetes.io/instance: uptime-kuma
spec:
  endpoints:
    - port: http
      path: /metrics
      interval: 60s
      scrapeTimeout: 10s
      basicAuth:
        username:
          name: uptime-kuma-metrics-auth
          key: username
        password:
          name: uptime-kuma-metrics-auth
          key: password
  namespaceSelector:
    matchNames:
      - uptime-kuma
  selector:
    matchLabels:
      app.kubernetes.io/name: uptime-kuma
      app.kubernetes.io/instance: uptime-kuma
