apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: localstack-ingress
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`localstack.shivpatel.xyz`)
      kind: Rule
      services:
        - name: localstack
          port: 4566
  tls: {}
