apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: localstack-auth-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: localstack-auth-secret
    creationPolicy: Owner
  data:
    - secretKey: LOCALSTACK_AUTH_TOKEN
      remoteRef:
        key: secret/data/localstack/auth
        property: auth-token
