apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memos-db-secret
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: memos-db-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: secret/data/postgresql/memos
        property: username
    - secretKey: password
      remoteRef:
        key: secret/data/postgresql/memos
        property: password
