apiVersion: v1
kind: Secret
metadata:
  name: postgresql
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.auth.password | quote }}
  POSTGRES_DB: {{ .Values.auth.database | quote }}
