apiVersion: batch/v1
kind: Job
metadata:
  name: postgresql-setup
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: immich-db-secret
          secret:
            secretName: immich-db-secret
        - name: n8n-db-secret
          secret:
            secretName: n8n-db-secret
        - name: terraform-db-secret
          secret:
            secretName: terraform-db-secret
        - name: teslamate-db-secret
          secret:
            secretName: teslamate-db-secret
        - name: authentik-db-secret
          secret:
            secretName: authentik-db-secret
        - name: gitea-db-secret
          secret:
            secretName: gitea-db-secret
        - name: gitlab-db-secret
          secret:
            secretName: gitlab-db-secret
        - name: datadog-db-secret
          secret:
            secretName: datadog-db-secret
      containers:
        - name: setup
          image: ghcr.io/cloudnative-pg/postgresql:17
          env:
            - name: PGHOST
              value: postgresql-rw.postgresql.svc.cluster.local
            # CNPG auto-generates this secret: <cluster-name>-superuser
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgresql-superuser
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-superuser
                  key: password
          volumeMounts:
            - name: immich-db-secret
              mountPath: /run/secrets/immich-db-secret
            - name: n8n-db-secret
              mountPath: /run/secrets/n8n-db-secret
            - name: terraform-db-secret
              mountPath: /run/secrets/terraform-db-secret
            - name: teslamate-db-secret
              mountPath: /run/secrets/teslamate-db-secret
            - name: authentik-db-secret
              mountPath: /run/secrets/authentik-db-secret
            - name: gitea-db-secret
              mountPath: /run/secrets/gitea-db-secret
            - name: gitlab-db-secret
              mountPath: /run/secrets/gitlab-db-secret
            - name: datadog-db-secret
              mountPath: /run/secrets/datadog-db-secret
          command:
            - /bin/bash
            - -c
            - |
              set -e

              # Wait for PostgreSQL to be ready
              until pg_isready -h $PGHOST -p 5432 -U $PGUSER; do
                echo "Waiting for PostgreSQL..."
                sleep 2
              done

              # Ensure all users and databases exist (non-destructive)
              for app in immich n8n terraform teslamate authentik gitea gitlab datadog; do
                echo "Ensuring $app user and database exist..."
                psql -c "DO \$\$ BEGIN CREATE USER $app WITH PASSWORD 'temp'; EXCEPTION WHEN duplicate_object THEN NULL; END \$\$;"                
                # Check if database exists, but don't recreate it if it has data
                DB_EXISTS=$(psql -tAc "SELECT 1 FROM pg_database WHERE datname='$app'" 2>/dev/null || echo "")
                if [ -z "$DB_EXISTS" ]; then
                  echo "Creating database $app..."
                  psql -c "CREATE DATABASE $app OWNER $app;"
                else
                  echo "Database $app already exists, skipping creation"
                fi
              done

              echo "Setting up immich database..."
              psql -d immich -c "CREATE EXTENSION IF NOT EXISTS cube;"
              psql -d immich -c "CREATE EXTENSION IF NOT EXISTS earthdistance;"
              psql -d immich -c "CREATE EXTENSION IF NOT EXISTS vector;"
              psql -d immich -c "ALTER SCHEMA public OWNER TO immich;"
              psql -d immich -c "GRANT ALL ON SCHEMA public TO immich;"

              echo "Setting up n8n database..."
              psql -d n8n -c "ALTER SCHEMA public OWNER TO n8n;"
              psql -d n8n -c "GRANT ALL ON SCHEMA public TO n8n;"

              echo "Setting up terraform database..."
              psql -d terraform -c "ALTER SCHEMA public OWNER TO terraform;"
              psql -d terraform -c "GRANT ALL ON SCHEMA public TO terraform;"

              echo "Setting up teslamate database..."
              # TeslaMate migrations drop/recreate geo extensions; do it here with superuser
              psql -d teslamate -c "DROP EXTENSION IF EXISTS earthdistance CASCADE;"
              psql -d teslamate -c "DROP EXTENSION IF EXISTS cube CASCADE;"
              psql -d teslamate -c "CREATE EXTENSION cube WITH SCHEMA public;"
              psql -d teslamate -c "CREATE EXTENSION earthdistance WITH SCHEMA public;"
              # Ensure extension is on latest version for TeslaMate migrations
              psql -d teslamate -c "ALTER EXTENSION earthdistance UPDATE;"
              # Give the application user ownership so future migrations can modify objects
              psql -d teslamate -c "ALTER FUNCTION ll_to_earth(double precision, double precision) OWNER TO teslamate;"
              psql -d teslamate -c "ALTER FUNCTION earth_box(earth, double precision) OWNER TO teslamate;"
              psql -d teslamate -c "ALTER SCHEMA public OWNER TO teslamate;"
              psql -d teslamate -c "GRANT ALL ON SCHEMA public TO teslamate;"
              # Mark TeslaMate migration 20240929084639 as applied so it doesn't re-drop extensions
              psql -d teslamate -c "INSERT INTO schema_migrations (version, inserted_at) VALUES ('20240929084639', NOW()) ON CONFLICT (version) DO NOTHING;"
              # Mark TeslaMate migration 20250407155134 (earthdistance upgrade) as complete
              psql -d teslamate -c "INSERT INTO schema_migrations (version, inserted_at) VALUES ('20250407155134', NOW()) ON CONFLICT (version) DO NOTHING;"

              echo "Setting up authentik database..."
              psql -d authentik -c "ALTER SCHEMA public OWNER TO authentik;"
              psql -d authentik -c "GRANT ALL ON SCHEMA public TO authentik;"

              echo "Setting up gitea database..."
              psql -d gitea -c "ALTER SCHEMA public OWNER TO gitea;"
              psql -d gitea -c "GRANT ALL ON SCHEMA public TO gitea;"

              echo "Setting up gitlab database..."
              psql -d gitlab -c "ALTER SCHEMA public OWNER TO gitlab;"
              psql -d gitlab -c "GRANT ALL ON SCHEMA public TO gitlab;"

              echo "Setting up Datadog Database Monitoring..."
              # Grant pg_monitor role to datadog user (cluster-wide)
              psql -c "ALTER ROLE datadog INHERIT;"
              psql -c "GRANT pg_monitor TO datadog;"

              # NOTE: pg_stat_statements extension is auto-managed by CNPG when pg_stat_statements.* params are set
              # Do NOT create/drop it here - CNPG handles CREATE/DROP EXTENSION in all databases

              # Setup datadog schema and functions in ALL databases for DBM
              for db in postgres immich n8n terraform teslamate authentik gitea gitlab datadog; do
                echo "Setting up Datadog monitoring in $db database..."
                
                # Create datadog schema
                psql -d $db -c "CREATE SCHEMA IF NOT EXISTS datadog;"
                psql -d $db -c "GRANT USAGE ON SCHEMA datadog TO datadog;"
                psql -d $db -c "GRANT USAGE ON SCHEMA public TO datadog;"
                
                # Create function to read pg_stat_activity
                psql -d $db -c "CREATE OR REPLACE FUNCTION datadog.pg_stat_activity()
                  RETURNS SETOF pg_stat_activity AS \$\$
                    SELECT * FROM pg_catalog.pg_stat_activity;
                  \$\$ LANGUAGE sql SECURITY DEFINER;"
                
                # Create function to read pg_stat_statements
                psql -d $db -c "CREATE OR REPLACE FUNCTION datadog.pg_stat_statements()
                  RETURNS SETOF pg_stat_statements AS \$\$
                    SELECT * FROM pg_stat_statements;
                  \$\$ LANGUAGE sql SECURITY DEFINER;"
                
                # Create function for explain plans
                psql -d $db -c "CREATE OR REPLACE FUNCTION datadog.explain_statement(
                    l_query TEXT,
                    OUT explain JSON
                  )
                  RETURNS SETOF JSON AS \$\$
                  DECLARE
                    curs REFCURSOR;
                    plan JSON;
                  BEGIN
                    SET TRANSACTION READ ONLY;
                    OPEN curs FOR EXECUTE pg_catalog.concat('EXPLAIN (FORMAT JSON) ', l_query);
                    FETCH curs INTO plan;
                    CLOSE curs;
                    RETURN QUERY SELECT plan;
                  END;
                  \$\$ LANGUAGE 'plpgsql' RETURNS NULL ON NULL INPUT SECURITY DEFINER;"
              done

              # Sync passwords from ExternalSecrets to database users
              echo "Syncing passwords from ExternalSecrets..."
              # Read secrets directly from mounted files or environment variables
              for app in immich n8n terraform teslamate authentik gitea gitlab datadog; do
                echo "Syncing password for $app..."
                # Use environment variables or mount secrets as files
                PASSWORD=$(cat /run/secrets/${app}-db-secret/password 2>/dev/null || echo "")
                if [ -z "$PASSWORD" ]; then
                  echo "Warning: Could not read password for $app, keeping existing password"
                else
                  psql -c "ALTER USER $app WITH PASSWORD '$PASSWORD';"
                fi
              done

              echo "Setup complete!"
