apiVersion: v2
name: harbor
description: A Helm chart for Harbor

type: application

version: 0.1.0

appVersion: "2.14.0"

dependencies:
  - name: harbor
    repository: https://helm.goharbor.io
    version: 1.18.2
