apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: teslamate-encryption-key-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: teslamate-encryption-key-secret
    creationPolicy: Owner
  data:
    - secretKey: encryption-key
      remoteRef:
        key: secret/data/teslamate
        property: encryption-key
