kind: "DatadogAgent"
apiVersion: "datadoghq.com/v2alpha1"
metadata:
  name: "datadog"
spec:
  global:
    site: "datadoghq.com"
    credentials:
      apiSecret:
        secretName: "datadog-secret"
        keyName: "api-key"
      appSecret:
        secretName: "datadog-secret"
        keyName: "app-key"
    clusterName: "homelab"
  features:
    logCollection:
      enabled: true
      containerCollectAll: true
  override:
      nodeAgent:
        containers: 
          init-config:
            env:
              - name: DD_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: datadog-secret
                    key: api-key
          trace-agent:
            env:
              - name: DD_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: datadog-secret
                    key: api-key
              - name: DD_CLUSTER_AGENT_AUTH_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: datadog-token
                    key: token