apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rabbitmq-secret
  namespace: rabbitmq
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rabbitmq
    creationPolicy: Owner
  data:
    - secretKey: rabbitmq-password
      remoteRef:
        key: secret/data/rabbitmq
        property: password
    - secretKey: rabbitmq-erlang-cookie
      remoteRef:
        key: secret/data/rabbitmq
        property: erlang-cookie
