apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-actions-runner-auth
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: github-actions-runner-auth
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: github_token
      remoteRef:
        key: secret/data/github/actions-runner
        property: token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
