apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-datadog
  namespace: mongodb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mongodb-datadog
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secret/data/mongodb/datadog
        property: username
    - secretKey: password
      remoteRef:
        key: secret/data/mongodb/datadog
        property: password
