apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-auth
  namespace: mongodb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mongodb-auth
    creationPolicy: Owner
  data:
    - secretKey: mongodb-root-password
      remoteRef:
        key: secret/data/mongodb/root
        property: root_password
