apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radar-ingress
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`radar.shivpatel.xyz`)
      kind: Rule
      services:
        - name: radar
          port: 9280
  tls: {}
