minio:
  mode: distributed
  statefulset:
    replicaCount: 3
    drivesPerNode: 2
    updateStrategy:
      type: RollingUpdate
  extraEnvVars:
    - name: MINIO_BROWSER
      value: "on"
  auth:
    existingSecret: "minio-root-credentials"
    rootUserSecretKey: "root-user"
    rootPasswordSecretKey: "root-password"
  image:
    registry: docker.io
    repository: bitnamilegacy/minio
  extraArgs:
    - --console-address
    - :9001
  persistence:
    enabled: true
    storageClass: longhorn
    accessModes:
      - ReadWriteOnce
  service:
    ports:
      api: 9000
    extraPorts:
      - name: console
        port: 9001
        targetPort: 9001
  console:
    enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
