apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tunnel-token
  namespace: cloudflared
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: tunnel-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: secret/data/cloudflared/tunnel
        property: token