apiVersion: v2
name: redis
description: A Helm chart for Redis

type: application

version: 0.1.0

appVersion: "8.4.0"

dependencies:
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 24.1.6
