redis:
  global:
    security:
      allowInsecureImages: true
  image:
    registry: registry-1.docker.io
    repository: bitnamilegacy/redis
    tag: "latest@sha256:5927ff3702df7106bbb7dcc0f8e3d053d979253c3aecce53f07f40db990f823b"
    pullPolicy: IfNotPresent
  auth:
    existingSecret: redis-password-secret
  master:
    podAnnotations:
      ad.datadoghq.com/redis.checks: |
        {
          "redisdb": {
            "init_config": {},
            "instances": [
              {
                "host": "%%host%%",
                "port": "6379",
                "password": "ENC[k8s_secret@redis/redis-password-secret/redis-password]"
              }
            ]
          }
        }
      ad.datadoghq.com/redis.logs: |
        [
          {
            "source": "redis",
            "service": "redis"
          }
        ]
    persistence:
      enabled: true
  replica:
    replicaCount: 3
    podAnnotations:
      ad.datadoghq.com/redis.checks: |
        {
          "redisdb": {
            "init_config": {},
            "instances": [
              {
                "host": "%%host%%",
                "port": "6379",
                "password": "ENC[k8s_secret@redis/redis-password-secret/redis-password]"
              }
            ]
          }
        }
      ad.datadoghq.com/redis.logs: |
        [
          {
            "source": "redis",
            "service": "redis"
          }
        ]
    persistence:
      enabled: true
    updateStrategy:
      type: OnDelete
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
