apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-slack-webhook
  namespace: observability
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: alertmanager-slack-webhook
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: SLACK_WEBHOOK_URL
      remoteRef:
        key: secret/data/observability/alertmanager
        property: slackWebhookUrl
