apiVersion: v2
name: caretta
description: Caretta eBPF network flow collection for Radar
type: application
version: 0.1.0
appVersion: "v0.0.16"
dependencies:
  - name: caretta
    repository: https://helm.groundcover.com
    version: 0.0.16
