name: Build Datadog Agent Integrations

on:
  push:
    paths:
      - ".github/workflows/build-datadog-agent-emqx.yaml"
      - "apps/datadog/Dockerfile.emqx"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish Agent image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/datadog/Dockerfile.emqx
          platforms: linux/amd64
          push: true
          tags: ghcr.io/shivppatel/datadog-agent-emqx:7.73.0-jmx-emqx-1.1.0-grafana-1.0.0
          cache-from: type=gha
          cache-to: type=gha,mode=max
