apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-registry-storage
  namespace: gitlab
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gitlab-registry-storage
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config: |
          s3:
            accesskey: {{ `{{ .accesskey | quote }}` }}
            secretkey: {{ `{{ .secretkey | quote }}` }}
            region: us-east-1
            regionendpoint: http://minio.minio.svc.cluster.local:9000
            bucket: gitlab-registry
            secure: false
            v4auth: true
            forcepathstyle: true
            rootdirectory: /
          cache:
            blobdescriptor: inmemory
          delete:
            enabled: true
          redirect:
            disable: true
  data:
    - secretKey: accesskey
      remoteRef:
        key: secret/data/minio
        property: root-user
    - secretKey: secretkey
      remoteRef:
        key: secret/data/minio
        property: root-password
