apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-object-storage-secret
  namespace: gitlab
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gitlab-object-storage-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        connection: |
          provider: AWS
          region: us-east-1
          host: minio.minio.svc.cluster.local
          endpoint: http://minio.minio.svc.cluster.local:9000
          path_style: true
          aws_access_key_id: {{ .accesskey | quote }}
          aws_secret_access_key: {{ .secretkey | quote }}
        config: |
          [default]
          access_key = {{ .accesskey }}
          secret_key = {{ .secretkey }}
          bucket_location = us-east-1
          host_base = minio.minio.svc.cluster.local:9000
          host_bucket = minio.minio.svc.cluster.local:9000/%(bucket)
          default_mime_type = binary/octet-stream
          enable_multipart = True
          multipart_max_chunks = 10000
          multipart_chunk_size_mb = 128
          recursive = True
          recv_chunk = 65536
          send_chunk = 65536
          server_side_encryption = False
          signature_v2 = True
          socket_timeout = 300
          use_https = False
          use_mime_magic = False
          verbosity = WARNING
  data:
    - secretKey: accesskey
      remoteRef:
        key: secret/data/minio
        property: root-user
    - secretKey: secretkey
      remoteRef:
        key: secret/data/minio
        property: root-password
