apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-redis-secret
  namespace: gitlab
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gitlab-redis-secret
    creationPolicy: Owner
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: secret/data/redis
        property: redis-password
