kind: "DatadogAgent"
apiVersion: "datadoghq.com/v2alpha1"
metadata:
  name: "datadog"
spec:
  global:
    clusterName: "homelab"
    site: "datadoghq.com"
    kubelet:
      tlsVerify: false
    credentials:
      apiSecret:
        secretName: "datadog-secret"
        keyName: "api-key"
    # Enable secrets backend to read from Kubernetes secrets
    secretBackend:
      command: "/readsecret_multiple_providers.sh"
      enableGlobalPermissions: true
  features:
    clusterChecks:
      enabled: true
    orchestratorExplorer:
      enabled: true
    helmCheck:
      enabled: true
    # apm:
    #   instrumentation:
    #     enabled: true
    #     targets:
    #       - name: "default-target"
    #         ddTraceVersions:
    #           java: "1"
    #           python: "4"
    #           js: "5"
    #           php: "1"
    #           dotnet: "3"
    #           ruby: "2"
    #         ddTraceConfigs:
    #           - name: "DD_PROFILING_ENABLED"
    #             value: "auto"
    logCollection:
      enabled: true
      containerCollectAll: true
    asm:
      threats:
        enabled: true
      sca:
        enabled: true
      iast:
        enabled: true
    cws:
      enabled: true
    cspm:
      enabled: true
    sbom:
      enabled: true
      containerImage:
        enabled: true
      host:
        enabled: true
    usm:
      enabled: true
    npm:
      enabled: true
    liveProcessCollection:
      enabled: true
  override:
    clusterAgent:
      extraConfd:
        configDataMap:
          postgres.yaml: |-
            cluster_check: true
            init_config:
            instances:
              - dbm: true
                host: postgresql-rw.postgresql.svc.cluster.local
                port: 5432
                username: datadog
                password: ENC[k8s_secret@postgresql/datadog-db-secret/password]
                dbname: postgres
                tags:
                  - "env:homelab"
                  - "service:postgresql"
                  - "cluster:postgresql"
                # Enable database autodiscovery to monitor all databases
                database_autodiscovery:
                  enabled: true
                  include:
                    - ".*"
                collect_schemas:
                  enabled: true
                # Collect query metrics
                collect_activity_metrics: true
                collect_database_size_metrics: true
                # Query samples settings
                query_samples:
                  enabled: true
                query_metrics:
                  enabled: true
