apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: datadog-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: datadog-secret
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: secret/data/datadog/credentials
        property: api-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: datadog-token
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: datadog-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: secret/data/datadog/credentials
        property: token
