argo-cd:
  configs:
    params:
      server.insecure: "true"
      otlp.address: "alloy.observability.svc.cluster.local:4317"
      otlp.insecure: "true"
      controller.profile.enabled: "true"
      server.profile.enabled: "true"
      applicationsetcontroller.profile.enabled: "true"
    cm:
      accounts.readonly: apiKey
    rbac:
      policy.csv: "g, readonly, role:readonly"
  redis-ha:
    enabled: true
    redis:
      podAnnotations:
        ad.datadoghq.com/redis.checks: |
          {
            "redisdb": {
              "init_config": {},
              "instances": [
                {
                  "host": "%%host%%",
                  "port": "6379",
                  "password": "ENC[k8s_secret@argocd/argocd-redis/auth]"
                }
              ]
            }
          }
        ad.datadoghq.com/redis.logs: |
          [
            {
              "source": "redis",
              "service": "argocd-redis"
            }
          ]
        ad.datadoghq.com/sentinel.checks: |
          {
            "redisdb": {
              "init_config": {},
              "instances": [
                {
                  "host": "%%host%%",
                  "port": "26379",
                  "password": "ENC[k8s_secret@argocd/argocd-redis/auth]"
                }
              ]
            }
          }
        ad.datadoghq.com/sentinel.logs: |
          [
            {
              "source": "redis",
              "service": "argocd-redis-sentinel"
            }
          ]
        ad.datadoghq.com/split-brain-fix.metrics_exclude: "true"
        ad.datadoghq.com/split-brain-fix.logs: |
          [
            {
              "source": "redis",
              "service": "argocd-redis-split-brain"
            }
          ]
  controller:
    podAnnotations:
      profiles.grafana.com/cpu.scrape: "true"
      profiles.grafana.com/cpu.port_name: "metrics"
      profiles.grafana.com/memory.scrape: "true"
      profiles.grafana.com/memory.port_name: "metrics"
      profiles.grafana.com/goroutine.scrape: "true"
      profiles.grafana.com/goroutine.port_name: "metrics"
    replicas: 1
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  dex:
    metrics:
      enabled: false
      serviceMonitor:
        enabled: false
  redis:
    podAnnotations:
      ad.datadoghq.com/redis.checks: |
        {
          "redisdb": {
            "init_config": {},
            "instances": [
              {
                "host": "%%host%%",
                "port": "6379",
                "password": "ENC[k8s_secret@argocd/argocd-redis/auth]"
              }
            ]
          }
        }
      ad.datadoghq.com/redis.logs: |
        [
          {
            "source": "redis",
            "service": "argocd-redis"
          }
        ]
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  server:
    podAnnotations:
      profiles.grafana.com/cpu.scrape: "true"
      profiles.grafana.com/cpu.port_name: "metrics"
      profiles.grafana.com/memory.scrape: "true"
      profiles.grafana.com/memory.port_name: "metrics"
      profiles.grafana.com/goroutine.scrape: "true"
      profiles.grafana.com/goroutine.port_name: "metrics"
    autoscaling:
      enabled: true
      minReplicas: 2
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  repoServer:
    podAnnotations:
      profiles.grafana.com/cpu.scrape: "true"
      profiles.grafana.com/cpu.port_name: "metrics"
      profiles.grafana.com/memory.scrape: "true"
      profiles.grafana.com/memory.port_name: "metrics"
      profiles.grafana.com/goroutine.scrape: "true"
      profiles.grafana.com/goroutine.port_name: "metrics"
    autoscaling:
      enabled: true
      minReplicas: 2
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  applicationSet:
    replicas: 2
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  notifications:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
