argo-cd:
  configs:
    params:
      server.insecure: "true"
      otlp.address: "alloy.observability.svc.cluster.local:4317"
      otlp.insecure: "true"
      controller.profile.enabled: "true"
      server.profile.enabled: "true"
      applicationsetcontroller.profile.enabled: "true"
    cm:
      accounts.readonly: apiKey
    rbac:
      policy.csv: "g, readonly, role:readonly"
  redis-ha:
    enabled: true
    redis:
      podAnnotations:
        ad.datadoghq.com/redis.checks: |
          {
            "redisdb": {
              "init_config": {},
              "instances": [
                {
                  "host": "%%host%%",
                  "port": "6379",
                  "password": "ENC[k8s_secret@argocd/argocd-redis/auth]"
                }
              ]
            }
          }
        ad.datadoghq.com/redis.logs: |
          [
            {
              "source": "redis",
              "service": "argocd-redis"
            }
          ]
        ad.datadoghq.com/sentinel.checks: |
          {
            "redisdb": {
              "init_config": {},
              "instances": [
                {
                  "host": "%%host%%",
                  "port": "26379"
                }
              ]
            }
          }
        ad.datadoghq.com/sentinel.logs: |
          [
            {
              "source": "redis",
              "service": "argocd-redis-sentinel"
            }
          ]
        ad.datadoghq.com/split-brain-fix.metrics_exclude: "true"
        ad.datadoghq.com/split-brain-fix.logs: |
          [
            {
              "source": "redis",
              "service": "argocd-redis-split-brain"
            }
          ]
  controller:
    podAnnotations:
      ad.datadoghq.com/application-controller.checks: |
        {
          "argocd": {
            "init_config": {},
            "instances": [
              {
                "app_controller_endpoint": "http://%%host%%:8082/metrics",
                "rename_labels": {
                  "name": "argocd_app_name"
                }
              }
            ]
          }
        }
      ad.datadoghq.com/application-controller.logs: |
        [
          {
            "source": "argocd",
            "service": "argocd-application-controller"
          }
        ]
      profiles.grafana.com/cpu.scrape: "true"
      profiles.grafana.com/cpu.port_name: "metrics"
      profiles.grafana.com/memory.scrape: "true"
      profiles.grafana.com/memory.port_name: "metrics"
      profiles.grafana.com/goroutine.scrape: "true"
      profiles.grafana.com/goroutine.port_name: "metrics"
    replicas: 1
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  dex:
    podAnnotations:
      ad.datadoghq.com/dex-server.logs: |
        [
          {
            "source": "argocd",
            "service": "argocd-dex"
          }
        ]
    metrics:
      enabled: false
      serviceMonitor:
        enabled: false
  redis:
    podAnnotations:
      ad.datadoghq.com/redis.checks: |
        {
          "redisdb": {
            "init_config": {},
            "instances": [
              {
                "host": "%%host%%",
                "port": "6379",
                "password": "ENC[k8s_secret@argocd/argocd-redis/auth]"
              }
            ]
          }
        }
      ad.datadoghq.com/redis.logs: |
        [
          {
            "source": "redis",
            "service": "argocd-redis"
          }
        ]
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  server:
    podAnnotations:
      ad.datadoghq.com/server.checks: |
        {
          "argocd": {
            "init_config": {},
            "instances": [
              {
                "api_server_endpoint": "http://%%host%%:8083/metrics"
              }
            ]
          }
        }
      ad.datadoghq.com/server.logs: |
        [
          {
            "source": "argocd",
            "service": "argocd-server"
          }
        ]
      profiles.grafana.com/cpu.scrape: "true"
      profiles.grafana.com/cpu.port_name: "metrics"
      profiles.grafana.com/memory.scrape: "true"
      profiles.grafana.com/memory.port_name: "metrics"
      profiles.grafana.com/goroutine.scrape: "true"
      profiles.grafana.com/goroutine.port_name: "metrics"
    autoscaling:
      enabled: true
      minReplicas: 2
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  repoServer:
    podAnnotations:
      ad.datadoghq.com/repo-server.checks: |
        {
          "argocd": {
            "init_config": {},
            "instances": [
              {
                "repo_server_endpoint": "http://%%host%%:8084/metrics"
              }
            ]
          }
        }
      ad.datadoghq.com/repo-server.logs: |
        [
          {
            "source": "argocd",
            "service": "argocd-repo-server"
          }
        ]
      profiles.grafana.com/cpu.scrape: "true"
      profiles.grafana.com/cpu.port_name: "metrics"
      profiles.grafana.com/memory.scrape: "true"
      profiles.grafana.com/memory.port_name: "metrics"
      profiles.grafana.com/goroutine.scrape: "true"
      profiles.grafana.com/goroutine.port_name: "metrics"
    autoscaling:
      enabled: true
      minReplicas: 2
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  applicationSet:
    podAnnotations:
      ad.datadoghq.com/applicationset-controller.checks: |
        {
          "argocd": {
            "init_config": {},
            "instances": [
              {
                "appset_controller_endpoint": "http://%%host%%:8080/metrics"
              }
            ]
          }
        }
      ad.datadoghq.com/applicationset-controller.logs: |
        [
          {
            "source": "argocd",
            "service": "argocd-applicationset-controller"
          }
        ]
    replicas: 2
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  notifications:
    podAnnotations:
      ad.datadoghq.com/notifications-controller.checks: |
        {
          "argocd": {
            "init_config": {},
            "instances": [
              {
                "notifications_controller_endpoint": "http://%%host%%:9001/metrics"
              }
            ]
          }
        }
      ad.datadoghq.com/notifications-controller.logs: |
        [
          {
            "source": "argocd",
            "service": "argocd-notifications-controller"
          }
        ]
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
